server:
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}

spring:
  jpa:
    defer-datasource-initialization: true

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    audience: ${OKTA_OAUTH2_AUDIENCE}

