spring:
  data:
    rest:
      base-path: ${SPRING_DATA_REST_BASE_PATH}

  jpa:
    defer-datasource-initialization: true

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    audience: ${OKTA_OAUTH2_AUDIENCE}
